import type { Metadata } from "next";
import "../styles/globals.css";
import { Navbar } from "../components/Navbar/Navbar";

import Providers from "./providers";

import { getSession, SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { ThemeProvider } from "./ThemeProvider/ThemeProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({  children }) {
 
  return (
    <html lang="en">
      <head>
        {/* <script src="https://cdn.tailwindcss.com"></script> */}
      </head>
      <body>
        <ThemeProvider>
        <Providers>

          <Navbar visibleNav={undefined} />
          {children}
    
        </Providers>
        </ThemeProvider>

        
      </body>
    </html>
  );
}
