import type { Metadata } from 'next'
import '../styles/globals.css'
import { Navbar } from '../components/Navbar/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <head>
          {/*} <script src="https://cdn.tailwindcss.com"></script> */}
        </head>
        <body>
          <Navbar/>
          {children}
          
        </body>
      </html>
    )
  }